/**
 * Solar Dominion DLC — 카드 데이터 (38종)
 * Summon(11) / Augment(14) / Spell(13)
 * 테마: Solar / Holy / Light
 */

export const SOLAR_CARDS = [

  // ════════════════════════════════════════════════════
  // ── SUMMON (11) ──────────────────────────────────
  // ════════════════════════════════════════════════════
  {
    id: 'summon_divine_cannon',
    name: 'Divine Cannon',     nameKo: '신성 대포',
    type: 'summon', rarity: 'rare', cost: 4, icon: '🔱',
    desc:   'Place a Divine Cannon. 45 damage, single target. Applies Solar DoT (10 DPS for 3s) on each hit.',
    descKo: '신성 대포를 배치합니다. 피해 45, 단일 타겟. 명중 시 Solar DoT 부여 (초당 10 피해, 3초).',
    tower: 'divine_cannon', dlc: 'solar_dominion',
  },
  {
    id: 'summon_solar_scythe',
    name: '태양 낫',      nameKo: '태양 낫',
    type: 'summon', rarity: 'uncommon', cost: 4, icon: '⚜️',
    desc:   'Place a 태양 낫. Deals +50% bonus damage to enemies with 500+ HP. Ideal against tanky foes.',
    descKo: '태양 낫을 배치합니다. HP 500+ 적에게 +50% 추가 피해. 탱커형 적에게 최적.',
    tower: 'solar_scythe', dlc: 'solar_dominion',
  },
  {
    id: 'summon_light_prism',
    name: 'Light Prism',       nameKo: '빛의 프리즘',
    type: 'summon', rarity: 'uncommon', cost: 3, icon: '🌅',
    desc:   'Place a Light Prism. Low damage, but adjacent towers gain +20% damage and +10% attack speed (aura stacks max ×1.51).',
    descKo: '빛의 프리즘을 배치합니다. 낮은 피해지만 인접 타워 +20% 피해 +10% 공속 오라 (최대 ×1.51 스택).',
    tower: 'light_prism', dlc: 'solar_dominion',
  },
  {
    id: 'summon_crusader',
    name: 'Crusader',          nameKo: '성전사',
    type: 'summon', rarity: 'uncommon', cost: 3, icon: '🏺',
    desc:   'Place a Crusader. Splash attacks stun all hit enemies for 400ms (3s cooldown per enemy). No stun on bosses.',
    descKo: '성전사를 배치합니다. 범위 공격으로 명중한 모든 적을 400ms 스턴 (적당 3초 쿨다운). 보스 스턴 불가.',
    tower: 'crusader', dlc: 'solar_dominion',
  },
  {
    id: 'summon_solar_fortress',
    name: 'Solar Fortress',    nameKo: '태양 요새',
    type: 'summon', rarity: 'rare', cost: 5, icon: '🌟',
    desc:   'Place a Solar Fortress. High damage Divine Cannon variant with extended range and +25% attack speed.',
    descKo: '태양 요새를 배치합니다. 확장된 사거리와 +25% 공속을 가진 강화형 신성 대포.',
    tower: 'divine_cannon', dlc: 'solar_dominion',
  },
  {
    id: 'summon_gilded_scythe',
    name: 'Gilded Scythe',     nameKo: '황금 낫',
    type: 'summon', rarity: 'rare', cost: 5, icon: '✨',
    desc:   'Place a Gilded Scythe. Enhanced 태양 낫 with +80% bonus damage vs HP 500+ and extended range.',
    descKo: '황금 낫을 배치합니다. HP 500+ 적에게 +80% 추가 피해 및 확장 사거리 강화형 태양 낫.',
    tower: 'solar_scythe', dlc: 'solar_dominion',
  },
  {
    id: 'summon_solar_pillar',
    name: 'Solar Pillar',      nameKo: '태양 기둥',
    type: 'summon', rarity: 'uncommon', cost: 4, icon: '☀️',
    desc:   'Place a Solar Pillar. Light Prism variant with larger aura radius (+1 hex) and stronger bonus (+25% dmg).',
    descKo: '태양 기둥을 배치합니다. 더 넓은 오라 반경(+1헥스)과 강화된 보너스(+25% 피해)를 가진 빛의 프리즘 변형.',
    tower: 'light_prism', dlc: 'solar_dominion',
  },
  {
    id: 'summon_holy_paladin',
    name: 'Holy Paladin',      nameKo: '성기사',
    type: 'summon', rarity: 'uncommon', cost: 4, icon: '🏺',
    desc:   'Place a Holy Paladin. Crusader variant with larger splash radius (1.5) and +600ms stun duration.',
    descKo: '성기사를 배치합니다. 더 넓은 범위 반경(1.5)과 +600ms 스턴 지속을 가진 성전사 변형.',
    tower: 'crusader', dlc: 'solar_dominion',
  },
  {
    id: 'summon_sun_archer',
    name: 'Sun Archer',        nameKo: '태양 궁수',
    type: 'summon', rarity: 'common', cost: 2, icon: '🏹',
    desc:   'Place a Sun Archer. Cheap Solar tower. Fast attack with moderate damage. Applies minor Solar DoT on hit.',
    descKo: '태양 궁수를 배치합니다. 저렴한 Solar 타워. 빠른 공속과 중간 피해. 명중 시 소량의 Solar DoT 부여.',
    tower: 'archer', dlc: 'solar_dominion',
  },
  {
    id: 'summon_blazing_turret',
    name: 'Blazing Turret',    nameKo: '불꽃 포탑',
    type: 'summon', rarity: 'common', cost: 2, icon: '🔥',
    desc:   'Place a Blazing Turret. Fast-firing Solar cannon with low damage. Great vs swarming enemies.',
    descKo: '불꽃 포탑을 배치합니다. 빠르게 발사하는 저피해 Solar 대포. 무리 적에게 효과적.',
    tower: 'cannon', dlc: 'solar_dominion',
  },
  {
    id: 'summon_golden_bulwark',
    name: 'Golden Bulwark',    nameKo: '황금 방벽',
    type: 'summon', rarity: 'rare', cost: 5, icon: '🏆',
    desc:   'Place a Golden Bulwark. Very slow but devastating Solar tower. Hits deal 200% damage to all enemies in splash.',
    descKo: '황금 방벽을 배치합니다. 매우 느리지만 강력한 Solar 타워. 범위 내 모든 적에게 200% 피해.',
    tower: 'ballista', dlc: 'solar_dominion',
  },

  // ════════════════════════════════════════════════════
  // ── AUGMENT (14) ─────────────────────────────────
  // ════════════════════════════════════════════════════
  {
    id: 'aug_radiant_edge',
    name: 'Radiant Edge',      nameKo: '빛의 날',
    type: 'augment', rarity: 'common', cost: 2, icon: '⚡',
    desc:   'All towers deal +18% damage for the next wave.',
    descKo: '다음 웨이브 동안 모든 타워 피해 +18%.',
    effect: { type: 'temp_dmg_bonus', mult: 1.18, waves: 1 }, dlc: 'solar_dominion',
  },
  {
    id: 'aug_solar_mantle',
    name: 'Solar Mantle',      nameKo: '태양 망토',
    type: 'augment', rarity: 'uncommon', cost: 2, icon: '🔆',
    desc:   'Selected tower gains +35% attack range permanently.',
    descKo: '선택한 타워의 공격 사거리가 영구적으로 +35% 증가합니다.',
    effect: { type: 'target_range_bonus', mult: 1.35 }, dlc: 'solar_dominion',
  },
  {
    id: 'aug_beacon_light',
    name: 'Beacon Light',      nameKo: '등대의 빛',
    type: 'augment', rarity: 'common', cost: 2, icon: '🌟',
    desc:   'All towers attack 12% faster permanently.',
    descKo: '모든 타워가 영구적으로 12% 더 빠르게 공격합니다.',
    effect: { type: 'tower_speed_bonus', towerType: '__all__', mult: 0.88 }, dlc: 'solar_dominion',
  },
  {
    id: 'aug_solar_focus',
    name: 'Solar Focus',       nameKo: '태양 집중',
    type: 'augment', rarity: 'uncommon', cost: 3, icon: '🎯',
    desc:   'Divine Cannon towers deal +45% damage permanently.',
    descKo: '신성 대포 타워의 피해가 영구적으로 +45% 증가합니다.',
    effect: { type: 'tower_dmg_bonus', towerType: 'divine_cannon', mult: 1.45 }, dlc: 'solar_dominion',
  },
  {
    id: 'aug_heavenly_armor',
    name: "Heaven's Armor",    nameKo: '천상의 갑옷',
    type: 'augment', rarity: 'uncommon', cost: 3, icon: '🛡️',
    desc:   'Crusader towers deal +30% damage and apply +200ms longer stuns.',
    descKo: '성전사 타워 피해 +30% 및 스턴 지속 +200ms.',
    effect: { type: 'crusader_stun_bonus', extraMs: 200, dmgMult: 1.30 }, dlc: 'solar_dominion',
  },
  {
    id: 'aug_gilded_edge',
    name: 'Gilded Edge',       nameKo: '황금 날',
    type: 'augment', rarity: 'uncommon', cost: 3, icon: '⚔️',
    desc:   '태양 낫 towers deal +70% damage to enemies with 500+ HP.',
    descKo: '태양 낫 타워의 HP 500+ 적 추가 피해 +70%.',
    effect: { type: 'tower_dmg_bonus', towerType: 'solar_scythe', mult: 1.45 }, dlc: 'solar_dominion',
  },
  {
    id: 'aug_prism_lens',
    name: 'Prism Lens',        nameKo: '프리즘 렌즈',
    type: 'augment', rarity: 'uncommon', cost: 2, icon: '🔮',
    desc:   'Light Prism aura extends 1 additional hex in radius.',
    descKo: '빛의 프리즘 오라 반경이 1헥스 추가 확장됩니다.',
    effect: { type: 'light_prism_bonus', extraDmg: 0.05, extraRadius: 1 }, dlc: 'solar_dominion',
  },
  {
    id: 'aug_holy_ground',
    name: 'Holy Ground',       nameKo: '성스러운 땅',
    type: 'augment', rarity: 'common', cost: 2, icon: '✨',
    desc:   'Selected tower position hex: all enemies passing through take +30% damage from that tower.',
    descKo: '선택한 타워 포지션: 그 타워의 피해 +30% 영구 강화.',
    effect: { type: 'tower_dmg_bonus', towerType: '__target__', mult: 1.30 }, dlc: 'solar_dominion',
  },
  {
    id: 'aug_solar_covenant',
    name: 'Solar Covenant',    nameKo: '태양 서약',
    type: 'augment', rarity: 'rare', cost: 4, icon: '📜',
    desc:   'All Solar-tagged towers deal +25% damage permanently.',
    descKo: '모든 Solar 태그 타워 피해 영구 +25%.',
    effect: { type: 'solar_pact', extraMult: 0.25, towerTag: 'Solar' }, dlc: 'solar_dominion',
  },
  {
    id: 'aug_divine_blessing',
    name: 'Divine Blessing',   nameKo: '신성한 축복',
    type: 'augment', rarity: 'rare', cost: 3, icon: '🌟',
    desc:   'Restore 1 Nexus HP.',
    descKo: '넥서스 HP를 1 회복합니다.',
    effect: { type: 'heal_nexus', amount: 1 }, dlc: 'solar_dominion',
  },
  {
    id: 'aug_sunsteel_core',
    name: 'Sunsteel Core',     nameKo: '태양강 코어',
    type: 'augment', rarity: 'uncommon', cost: 2, icon: '🔥',
    desc:   '태양 낫 tanks-lane bonus: +80% damage vs HP 500+ for the next wave only.',
    descKo: '다음 웨이브 동안 태양 낫 HP 500+ 적 피해 +80%.',
    effect: { type: 'temp_dmg_bonus', mult: 1.40, waves: 1 }, dlc: 'solar_dominion',
  },
  {
    id: 'aug_blazing_resolve',
    name: 'Blazing Resolve',   nameKo: '불굴의 의지',
    type: 'augment', rarity: 'common', cost: 2, icon: '💪',
    desc:   'Next wave enemies move 20% slower and you gain 5 extra seconds of prep time.',
    descKo: '다음 웨이브 적이 20% 느리게 이동하고 준비 시간 5초 추가.',
    effect: { type: 'slow_next_wave', amount: 0.20, extraPrep: 5000 }, dlc: 'solar_dominion',
  },
  {
    id: 'aug_golden_decree',
    name: 'Golden Decree',     nameKo: '황금 칙령',
    type: 'augment', rarity: 'common', cost: 0, icon: '💰',
    desc:   'Gain +18 gold.',
    descKo: '+18 골드를 획득합니다.',
    effect: { type: 'gold', amount: 18 }, dlc: 'solar_dominion',
  },
  {
    id: 'aug_solar_pact',
    name: 'Solar Pact',        nameKo: '태양 협약',
    type: 'augment', rarity: 'uncommon', cost: 3, icon: '🌅',
    desc:   'All Holy-tagged towers deal +20% damage and their attacks apply minor Solar DoT.',
    descKo: '모든 Holy 태그 타워 피해 +20%, 공격 시 소량 Solar DoT 추가.',
    effect: { type: 'solar_pact', extraMult: 0.20, towerTag: 'Holy' }, dlc: 'solar_dominion',
  },

  // ════════════════════════════════════════════════════
  // ── SPELL (13) ───────────────────────────────────
  // ════════════════════════════════════════════════════
  {
    id: 'spell_solar_beam',
    name: 'Solar Beam',        nameKo: '태양 광선',
    type: 'spell', rarity: 'rare', cost: 4, icon: '☀️',
    desc:   'Deal 50 damage to all enemies and slow them 30% for 3 seconds. (30% slow does not ground flying enemies.)',
    descKo: '모든 적에게 50 피해를 입히고 3초 동안 30% 감속합니다. (30% 감속은 비행 적을 착지시키지 않습니다.)',
    effect: { type: 'solar_beam', damage: 50, slow: 0.30, slowDur: 3000 }, dlc: 'solar_dominion',
  },
  {
    id: 'spell_divine_shield',
    name: 'Divine Shield',     nameKo: '신성 방패',
    type: 'spell', rarity: 'rare', cost: 5, icon: '🛡️',
    desc:   'The Nexus becomes immune to all damage for 10 seconds.',
    descKo: '넥서스가 10초 동안 모든 피해에 면역이 됩니다.',
    effect: { type: 'divine_shield', duration: 10000 }, dlc: 'solar_dominion',
  },
  {
    id: 'spell_solar_flare',
    name: 'Solar Flare',       nameKo: '태양 폭발',
    type: 'spell', rarity: 'uncommon', cost: 3, icon: '🌟',
    desc:   'Apply Solar DoT (15 DPS for 4s) to all enemies. solarImmune enemies are unaffected.',
    descKo: '모든 적에게 Solar DoT를 부여합니다 (초당 15 피해, 4초). solarImmune 적에게는 효과 없음.',
    effect: { type: 'solar_dot_all', dps: 15, duration: 4000 }, dlc: 'solar_dominion',
  },
  {
    id: 'spell_solar_tithe',
    name: 'Solar Tithe',       nameKo: '태양 십일조',
    type: 'spell', rarity: 'uncommon', cost: 2, icon: '💸',
    desc:   'Spend 25% of your gold. All enemies take ×2 damage for 5 seconds.',
    descKo: '보유 골드의 25%를 소비합니다. 모든 적이 5초 동안 2배 피해를 받습니다.',
    effect: { type: 'solar_tithe', goldPct: 0.25, damageMult: 2.0, duration: 5000 }, dlc: 'solar_dominion',
  },
  {
    id: 'spell_radiant_burst',
    name: 'Radiant Burst',     nameKo: '빛의 폭발',
    type: 'spell', rarity: 'uncommon', cost: 3, icon: '💥',
    desc:   'Deal 30 damage to all enemies on the field.',
    descKo: '전장의 모든 적에게 30 피해를 입힙니다.',
    effect: { type: 'damage_all', amount: 30 }, dlc: 'solar_dominion',
  },
  {
    id: 'spell_sunburst',
    name: 'Sunburst',          nameKo: '태양 섬광',
    type: 'spell', rarity: 'common', cost: 2, icon: '🌅',
    desc:   'Deal 25 damage to the lead enemy and slow it 40% for 4 seconds.',
    descKo: '선두 적에게 25 피해를 입히고 4초 동안 40% 감속합니다.',
    effect: { type: 'damage_lead', amount: 25, slow: 0.40, slowDur: 4000 }, dlc: 'solar_dominion',
  },
  {
    id: 'spell_gold_tithe',
    name: 'Gold Tithe',        nameKo: '황금 십일조',
    type: 'spell', rarity: 'common', cost: 2, icon: '💰',
    desc:   'Gain gold equal to the number of enemies currently on the field × 2.',
    descKo: '현재 전장의 적 수 × 2만큼 골드를 획득합니다.',
    effect: { type: 'gold_per_enemy', mult: 2 }, dlc: 'solar_dominion',
  },
  {
    id: 'spell_solar_nova',
    name: 'Solar Nova',        nameKo: '태양 노바',
    type: 'spell', rarity: 'common', cost: 2, icon: '🌠',
    desc:   'Deal 20 damage to all enemies. Any already burning from Solar DoT take double damage.',
    descKo: '모든 적에게 20 피해. Solar DoT 중인 적은 2배 피해를 받습니다.',
    effect: { type: 'damage_all_solar_bonus', amount: 20, solarBonusMult: 2.0 }, dlc: 'solar_dominion',
  },
  {
    id: 'spell_heavenly_light',
    name: 'Heavenly Light',    nameKo: '천상의 빛',
    type: 'spell', rarity: 'rare', cost: 3, icon: '✨',
    desc:   'Restore 1 Nexus HP and gain +10 gold.',
    descKo: '넥서스 HP 1 회복 및 +10 골드 획득.',
    effect: { type: 'heal_nexus_gold', healAmount: 1, goldAmount: 10 }, dlc: 'solar_dominion',
  },
  {
    id: 'spell_blinding_light',
    name: 'Blinding Light',    nameKo: '눈부신 빛',
    type: 'spell', rarity: 'rare', cost: 4, icon: '💫',
    desc:   'Freeze all enemies for 2.5 seconds.',
    descKo: '모든 적을 2.5초 동안 빙결시킵니다.',
    effect: { type: 'freeze_all', duration: 2500 }, dlc: 'solar_dominion',
  },
  {
    id: 'spell_solar_surge',
    name: 'Solar Surge',       nameKo: '태양 급등',
    type: 'spell', rarity: 'rare', cost: 4, icon: '⚡',
    desc:   'All towers attack 60% faster for 5 seconds.',
    descKo: '모든 타워가 5초 동안 60% 빠르게 공격합니다.',
    effect: { type: 'tower_speed_temp', mult: 0.625, duration: 5000 }, dlc: 'solar_dominion',
  },
  {
    id: 'spell_divine_wrath',
    name: 'Divine Wrath',      nameKo: '신성한 진노',
    type: 'spell', rarity: 'uncommon', cost: 3, icon: '🔱',
    desc:   'Deal 90 damage to the lead enemy.',
    descKo: '선두 적에게 90 피해를 입힙니다.',
    effect: { type: 'damage_lead', amount: 90 }, dlc: 'solar_dominion',
  },
  {
    id: 'spell_solar_corona',
    name: 'Solar Corona',      nameKo: '태양 코로나',
    type: 'spell', rarity: 'rare', cost: 4, icon: '🌞',
    desc:   'Apply Solar DoT (12 DPS for 3s) to all enemies AND grant +1 bonus Solar Charge.',
    descKo: '모든 적에게 Solar DoT 부여 (초당 12, 3초) + Solar Charge +1 보너스 충전.',
    effect: { type: 'solar_dot_all_charge', dps: 12, duration: 3000, bonusCharge: 1 }, dlc: 'solar_dominion',
  },
];
