/**
 * Shadow Realm DLC — 카드 데이터 (38종)
 * Summon(11) / Augment(14) / Spell(13)
 * 테마: Shadow / Void / Death
 */

export const SHADOW_CARDS = [

  // ════════════════════════════════════════════════════
  // ── SUMMON (10) ───────────────────────────────────
  // ════════════════════════════════════════════════════
  {
    id: 'summon_void_sentinel',
    name: 'Void Sentinel',     nameKo: '공허 파수꾼',     nameZh: '虚空哨兵',
    type: 'summon', rarity: 'rare', cost: 5, icon: '🌌',
    desc:   'Place a Void Sentinel. Very high damage, long range, slow attack. Ignores 25% of enemy defenses.',
    descKo: '공허 파수꾼을 배치합니다. 매우 높은 피해, 긴 사거리, 느린 공속. 적 방어력 25% 무시.',
    descZh: '放置一座虚空哨兵。伤害极高，射程极远，攻速缓慢。无视敌人25%的防御。',
    tower: 'void_sentinel', dlc: 'shadow_realm',
  },
  {
    id: 'summon_shadow_weaver',
    name: 'Shadow Weaver',     nameKo: '그림자 직조자',     nameZh: '暗影织网者',
    type: 'summon', rarity: 'uncommon', cost: 4, icon: '🕷️',
    desc:   'Place a Shadow Weaver. Fast attack, applies Shadow DoT (6 DPS for 3s) on each hit.',
    descKo: '그림자 직조자를 배치합니다. 빠른 공속, 명중 시 Shadow DoT 부여 (초당 6 피해, 3초).',
    descZh: '放置一座暗影织网者。攻速快，每次命中附加暗影持续伤害（每秒6点，持续3秒）。',
    tower: 'shadow_weaver', dlc: 'shadow_realm',
  },
  {
    id: 'summon_phantom_sniper',
    name: 'Phantom Sniper',    nameKo: '환영 저격수',    nameZh: '幻影狙击手',
    type: 'summon', rarity: 'rare', cost: 5, icon: '👁️',
    desc:   'Place a Phantom Sniper. Extreme range, massive damage, very slow attack. Deals 2× damage to slowed enemies.',
    descKo: '환영 저격수를 배치합니다. 극도의 사거리, 대피해, 매우 느린 공속. 감속 적에게 2배 피해.',
    descZh: '放置一名幻影狙击手。射程超远，伤害巨大，攻速极慢。对减速的敌人造成2倍伤害。',
    tower: 'phantom_sniper', dlc: 'shadow_realm',
  },
  {
    id: 'summon_void_sentinel_2',
    name: 'Void Obelisk',      nameKo: '공허 오벨리스크',      nameZh: '虚空方尖碑',
    type: 'summon', rarity: 'rare', cost: 5, icon: '🗿',
    desc:   'Place a Void Obelisk. Slow attack but passively slows all enemies in a large radius by 20%.',
    descKo: '공허 오벨리스크를 배치합니다. 느린 공속이지만 광역 범위 내 모든 적을 20% 지속 감속.',
    descZh: '放置一座虚空方尖碑。攻速缓慢，但使大范围内所有敌人持续减速20%。',
    tower: 'void_sentinel', dlc: 'shadow_realm',
  },
  {
    id: 'summon_shadow_cannon',
    name: 'Shadow Cannon',     nameKo: '그림자 대포',     nameZh: '暗影火炮',
    type: 'summon', rarity: 'uncommon', cost: 3, icon: '🕳️',
    desc:   'Place a Shadow Cannon. Splash damage + applies Shadow DoT to every enemy in the blast.',
    descKo: '그림자 대포를 배치합니다. 범위 피해 + 폭발 내 모든 적에게 Shadow DoT 부여.',
    descZh: '放置一座暗影火炮。溅射伤害+对爆炸范围内所有敌人附加暗影持续伤害。',
    tower: 'bone_archer', dlc: 'shadow_realm',
  },
  {
    id: 'summon_specter',
    name: 'Specter',           nameKo: '유령',           nameZh: '幽灵',
    type: 'summon', rarity: 'common', cost: 2, icon: '👻',
    desc:   'Place a Specter tower. Very fast attack, moderate damage. Cheapest Shadow tower.',
    descKo: '유령 타워를 배치합니다. 매우 빠른 공속, 중간 피해. 가장 저렴한 그림자 타워.',
    descZh: '放置一座幽灵塔。攻速极快，伤害中等。最便宜的暗影防御塔。',
    tower: 'bone_archer', dlc: 'shadow_realm',
  },
  {
    id: 'summon_death_knight',
    name: 'Death Knight',      nameKo: '죽음의 기사',      nameZh: '死亡骑士',
    type: 'summon', rarity: 'uncommon', cost: 4, icon: '💀',
    desc:   'Place a Death Knight. High damage, short range, very fast reload. Ideal at chokepoints.',
    descKo: '죽음의 기사를 배치합니다. 높은 피해, 짧은 사거리, 매우 빠른 재장전. 목 지점에 최적.',
    descZh: '放置一名死亡骑士。伤害高，射程短，装填极快。扼守要道的最佳选择。',
    tower: 'shadow_strike', dlc: 'shadow_realm',
  },
  {
    id: 'summon_void_mage',
    name: 'Void Mage',         nameKo: '공허 마법사',         nameZh: '虚空法师',
    type: 'summon', rarity: 'rare', cost: 5, icon: '🌀',
    desc:   'Place a Void Mage. Slows enemies 35% and deals bonus damage equal to 4% of their current HP.',
    descKo: '공허 마법사를 배치합니다. 적을 35% 감속하고 현재 HP의 4%에 해당하는 추가 피해.',
    descZh: '放置一名虚空法师。使敌人减速35%，并造成相当于其当前生命值4%的额外伤害。',
    tower: 'shadow_weaver', dlc: 'shadow_realm',
  },
  {
    id: 'summon_bone_golem',
    name: 'Bone Golem',        nameKo: '뼈 골렘',        nameZh: '白骨魔像',
    type: 'summon', rarity: 'common', cost: 3, icon: '🦴',
    desc:   'Place a Bone Golem. Very high splash damage, extremely slow attack. Best in crowds.',
    descKo: '뼈 골렘을 배치합니다. 매우 높은 범위 피해, 극도로 느린 공속. 다수 적에게 최적.',
    descZh: '放置一座白骨魔像。溅射伤害极高，攻速极其缓慢。对付敌群效果最佳。',
    tower: 'shadow_strike', dlc: 'shadow_realm',
  },
  {
    id: 'summon_phantom_archer',
    name: 'Phantom Archer',    nameKo: '환영 궁수',    nameZh: '幻影弓手',
    type: 'summon', rarity: 'uncommon', cost: 3, icon: '🏹',
    desc:   'Place a Phantom Archer. Moderate damage, fast attack. Shadow energy enhances every 5th shot.',
    descKo: '환영 궁수를 배치합니다. 중간 피해, 빠른 공속. 5번째 공격마다 그림자 에너지 강화.',
    descZh: '放置一名幻影弓手。伤害中等，攻速快。每第5次射击获得暗影能量强化。',
    tower: 'bone_archer', dlc: 'shadow_realm',
  },
  {
    id:     'summon_soul_reaper',
    name:   'Soul Reaper',     nameKo: '영혼 수확자',     nameZh: '灵魂收割者',
    type: 'summon', rarity: 'legendary', cost: 6, icon: '💀',
    desc:   'Place a Soul Reaper. Applies 60% slow (3.5s), 14 DPS shadow decay (6s), and 25% armor penetration. Minimal direct damage — extends enemy exposure time dramatically.',
    descKo: '영혼 수확자를 배치합니다. 60% 감속(3.5초), 초당 14 그림자 붕괴(6초), 방어력 25% 관통을 부여합니다. 직접 피해는 낮지만, 적의 사거리 노출 시간을 대폭 연장합니다.',
    descZh: '放置一名灵魂收割者。附加60%减速（3.5秒）、每秒14点暗影侵蚀（6秒）及25%护甲穿透。直接伤害极低——大幅延长敌人在射程内的暴露时间。',
    tower: 'soul_reaper', dlc: 'shadow_realm',
  },

  // ════════════════════════════════════════════════════
  // ── AUGMENT (14) ─────────────────────────────────
  // ════════════════════════════════════════════════════
  {
    id: 'aug_soul_rift',
    name: 'Soul Rift',         nameKo: '영혼 균열',         nameZh: '灵魂裂隙',
    type: 'augment', rarity: 'uncommon', cost: 3, icon: '💜',
    desc:   'Target tower gains +80% damage and +20% attack range.',
    descKo: '타워 피해 +80%, 사거리 +20%.',
    descZh: '目标防御塔伤害+80%，攻击范围+20%。',
    effect: { stats: [{ stat: 'damage', mult: 1.8 }, { stat: 'range', mult: 1.2 }] },
    dlc: 'shadow_realm',
  },
  {
    id: 'aug_void_edge',
    name: 'Void Edge',         nameKo: '공허의 날',         nameZh: '虚空之刃',
    type: 'augment', rarity: 'uncommon', cost: 3, icon: '🌑',
    desc:   'Target tower gains +100% damage but loses 20% attack range. Massive burst at close range.',
    descKo: '타워 피해 +100%, 사거리 -20%. 근거리에서 폭발적인 화력.',
    descZh: '目标防御塔伤害+100%，但攻击范围-20%。近距离火力惊人。',
    effect: { stats: [{ stat: 'damage', mult: 2.0 }, { stat: 'range', mult: 0.8 }] },
    dlc: 'shadow_realm',
  },
  {
    id: 'aug_shadow_surge',
    name: 'Shadow Surge',      nameKo: '그림자 파동',      nameZh: '暗影涌动',
    type: 'augment', rarity: 'common', cost: 2, icon: '🌒',
    desc:   'Target tower gains +50% damage and attacks 40% faster.',
    descKo: '타워 피해 +50%, 공격속도 40% 증가.',
    descZh: '目标防御塔伤害+50%，攻击速度提升40%。',
    effect: { stats: [{ stat: 'damage', mult: 1.5 }, { stat: 'attackSpeed', mult: 0.6 }] },
    dlc: 'shadow_realm',
  },
  {
    id: 'aug_phantom_step',
    name: 'Phantom Step',      nameKo: '환영의 발걸음',      nameZh: '幻影之步',
    type: 'augment', rarity: 'uncommon', cost: 3, icon: '👣',
    desc:   'Target tower gains +35% attack range and attacks 35% faster.',
    descKo: '타워 사거리 +35%, 공격속도 35% 증가.',
    descZh: '目标防御塔攻击范围+35%，攻击速度提升35%。',
    effect: { stats: [{ stat: 'range', mult: 1.35 }, { stat: 'attackSpeed', mult: 0.65 }] },
    dlc: 'shadow_realm',
  },
  {
    id: 'aug_void_infusion',
    name: 'Void Infusion',     nameKo: '공허 주입',     nameZh: '虚空灌注',
    type: 'augment', rarity: 'rare', cost: 5, icon: '🔯',
    desc:   'Target tower gains +300% attack range. Covers the entire map. Best on high-damage towers.',
    descKo: '타워 사거리 +300%. 전체 맵 커버. 고피해 타워에 최적.',
    descZh: '目标防御塔攻击范围+300%。覆盖整张地图。最适合高伤害防御塔。',
    effect: { stat: 'range', mult: 4.0 },
    dlc: 'shadow_realm',
  },
  {
    id: 'aug_entropy_core',
    name: 'Entropy Core',      nameKo: '엔트로피 코어',      nameZh: '熵变核心',
    type: 'augment', rarity: 'rare', cost: 4, icon: '♾️',
    desc:   'Target tower gains +80% damage and attacks 80% faster. Unstable but devastating.',
    descKo: '타워 피해 +80%, 공격속도 80% 증가. 불안정하지만 파괴적.',
    descZh: '目标防御塔伤害+80%，攻击速度提升80%。不稳定，却极具毁灭性。',
    effect: { stats: [{ stat: 'damage', mult: 1.8 }, { stat: 'attackSpeed', mult: 0.2 }] },
    dlc: 'shadow_realm',
  },
  {
    id: 'aug_soul_link',
    name: 'Soul Link',         nameKo: '영혼 연결',         nameZh: '灵魂链接',
    type: 'augment', rarity: 'common', cost: 2, icon: '🔗',
    desc:   'Target tower gains +40% damage and attacks 30% faster.',
    descKo: '타워 피해 +40%, 공격속도 30% 증가.',
    descZh: '目标防御塔伤害+40%，攻击速度提升30%。',
    effect: { stats: [{ stat: 'damage', mult: 1.4 }, { stat: 'attackSpeed', mult: 0.7 }] },
    dlc: 'shadow_realm',
  },
  {
    id: 'aug_shadow_aura',
    name: 'Shadow Aura',       nameKo: '그림자 오라',       nameZh: '暗影光环',
    type: 'augment', rarity: 'uncommon', cost: 3, icon: '🌫️',
    desc:   'Target tower gains +55% damage and +40% attack range. Radiates shadow energy.',
    descKo: '타워 피해 +55%, 사거리 +40%. 그림자 에너지를 방사합니다.',
    descZh: '目标防御塔伤害+55%，攻击范围+40%。散发暗影能量。',
    effect: { stats: [{ stat: 'damage', mult: 1.55 }, { stat: 'range', mult: 1.4 }] },
    dlc: 'shadow_realm',
  },
  {
    id: 'aug_phantom_mark',
    name: 'Phantom Mark',      nameKo: '환영의 낙인',      nameZh: '幻影烙印',
    type: 'augment', rarity: 'common', cost: 2, icon: '🔮',
    desc:   'Target tower gains +55% damage and attacks 35% faster.',
    descKo: '타워 피해 +55%, 공격속도 35% 증가.',
    descZh: '目标防御塔伤害+55%，攻击速度提升35%。',
    effect: { stats: [{ stat: 'damage', mult: 1.55 }, { stat: 'attackSpeed', mult: 0.65 }] },
    dlc: 'shadow_realm',
  },
  {
    id: 'aug_void_eye',
    name: 'Void Eye',          nameKo: '공허의 눈',          nameZh: '虚空之眼',
    type: 'augment', rarity: 'rare', cost: 4, icon: '👁️',
    desc:   'Target tower gains +120% damage. The void stares through every enemy.',
    descKo: '타워 피해 +120%. 공허가 모든 적을 꿰뚫어봅니다.',
    descZh: '目标防御塔伤害+120%。虚空洞穿一切敌人。',
    effect: { stat: 'damage', mult: 2.2 },
    dlc: 'shadow_realm',
  },
  {
    id: 'aug_shadow_speed',
    name: 'Shadow Speed',      nameKo: '그림자 속도',      nameZh: '暗影疾速',
    type: 'augment', rarity: 'common', cost: 2, icon: '💨',
    desc:   'Target tower attacks 60% faster. Move with the shadows.',
    descKo: '타워 공격속도 60% 증가. 그림자처럼 움직이세요.',
    descZh: '目标防御塔攻击速度提升60%。如影随行。',
    effect: { stat: 'attackSpeed', mult: 0.4 },
    dlc: 'shadow_realm',
  },
  {
    id: 'aug_death_essence',
    name: 'Death Essence',     nameKo: '죽음의 정수',     nameZh: '死亡精华',
    type: 'augment', rarity: 'uncommon', cost: 3, icon: '☠️',
    desc:   'Target tower gains +70% damage and +30% attack range.',
    descKo: '타워 피해 +70%, 사거리 +30%.',
    descZh: '目标防御塔伤害+70%，攻击范围+30%。',
    effect: { stats: [{ stat: 'damage', mult: 1.7 }, { stat: 'range', mult: 1.3 }] },
    dlc: 'shadow_realm',
  },
  {
    id: 'aug_void_mastery',
    name: 'Void Mastery',      nameKo: '공허 지배',      nameZh: '虚空支配',
    type: 'augment', rarity: 'rare', cost: 5, icon: '🌌',
    desc:   'Target tower gains +100% damage, +50% range, and attacks 50% faster. The ultimate void rune.',
    descKo: '타워 피해 +100%, 사거리 +50%, 공격속도 50% 증가. 최강의 공허 룬.',
    descZh: '目标防御塔伤害+100%，攻击范围+50%，攻击速度提升50%。终极虚空符文。',
    effect: { stats: [{ stat: 'damage', mult: 2.0 }, { stat: 'range', mult: 1.5 }, { stat: 'attackSpeed', mult: 0.5 }] },
    dlc: 'shadow_realm',
  },
  {
    id: 'aug_soul_rend',
    name: 'Soul Rend',         nameKo: '영혼 찢기',         nameZh: '灵魂撕裂',
    type: 'augment', rarity: 'uncommon', cost: 3, icon: '💔',
    desc:   'Target tower gains +90% damage but loses 25% attack range. Devastating at close quarters.',
    descKo: '타워 피해 +90%, 사거리 -25%. 근거리에서 파괴적.',
    descZh: '目标防御塔伤害+90%，但攻击范围-25%。近身作战极具毁灭性。',
    effect: { stats: [{ stat: 'damage', mult: 1.9 }, { stat: 'range', mult: 0.75 }] },
    dlc: 'shadow_realm',
  },

  // ════════════════════════════════════════════════════
  // ── SPELL (13) ────────────────────────────────────
  // ════════════════════════════════════════════════════
  {
    id: 'spell_darkness',
    name: 'Darkness',          nameKo: '어둠',          nameZh: '黑暗',
    type: 'spell', rarity: 'uncommon', cost: 3, icon: '🌑',
    desc:   'All enemies -40% speed and all towers +20% damage for 6 seconds.',
    descKo: '모든 적 이동속도 -40%, 모든 타워 피해 +20%, 6초 지속.',
    descZh: '所有敌人移动速度-40%，所有防御塔伤害+20%，持续6秒。',
    effect: { type: 'darkness', slowAmt: 0.4, dmgBoost: 0.2, duration: 6000 },
    dlc: 'shadow_realm',
  },
  {
    id: 'spell_shadow_nova',
    name: 'Shadow Nova',       nameKo: '그림자 노바',       nameZh: '暗影新星',
    type: 'spell', rarity: 'rare', cost: 5, icon: '💜',
    desc:   'Deal damage equal to 60% of each enemy\'s MISSING HP. Devastates wounded enemies.',
    descKo: '모든 적의 잃은 HP의 60%에 해당하는 피해. 부상 적에게 파괴적.',
    descZh: '对每个敌人造成相当于其已损失生命值60%的伤害。重创负伤的敌人。',
    effect: { type: 'shadow_nova', pct: 0.6 },
    dlc: 'shadow_realm',
  },
  {
    id: 'spell_void_pulse',
    name: 'Void Pulse',        nameKo: '공허 파동',        nameZh: '虚空脉冲',
    type: 'spell', rarity: 'uncommon', cost: 3, icon: '🔵',
    desc:   'Push the 3 furthest enemies back 3 hex steps toward spawn.',
    descKo: '가장 앞선 적 3명을 스폰 지점 방향으로 3칸 밀어냅니다.',
    descZh: '将最前方的3个敌人向出生点方向推回3格。',
    effect: { type: 'void_pulse', count: 3, steps: 3 },
    dlc: 'shadow_realm',
  },
  {
    id: 'spell_soul_feast',
    name: 'Soul Feast',        nameKo: '영혼 향연',        nameZh: '灵魂盛宴',
    type: 'spell', rarity: 'rare', cost: 4, icon: '💀',
    desc:   'Instantly kill all enemies below 25% HP. Gain 3 gold per enemy killed.',
    descKo: 'HP 25% 미만 적을 즉사. 처치한 적 1마리당 골드 3 획득.',
    descZh: '立即击杀生命值低于25%的所有敌人。每击杀1个敌人获得3金币。',
    effect: { type: 'soul_feast', hpThreshold: 0.25, goldPerKill: 3 },
    dlc: 'shadow_realm',
  },
  {
    id: 'spell_phantom_strike',
    name: 'Phantom Strike',    nameKo: '환영 강타',    nameZh: '幻影突袭',
    type: 'spell', rarity: 'common', cost: 2, icon: '👊',
    desc:   'Deal 80 damage to 3 random enemies.',
    descKo: '무작위 적 3명에게 80 피해.',
    descZh: '对3个随机敌人造成80点伤害。',
    effect: { type: 'damage_random', count: 3, amount: 80 },
    dlc: 'shadow_realm',
  },
  {
    id: 'spell_void_collapse',
    name: 'Void Collapse',     nameKo: '공허 붕괴',     nameZh: '虚空崩塌',
    type: 'spell', rarity: 'uncommon', cost: 3, icon: '🕳️',
    desc:   'Slow all enemies 65% for 8 seconds. The void swallows their speed.',
    descKo: '모든 적을 8초 동안 65% 감속. 공허가 속도를 삼킵니다.',
    descZh: '所有敌人减速65%，持续8秒。虚空吞噬他们的速度。',
    effect: { type: 'slow_all', amount: 0.65, duration: 8000 },
    dlc: 'shadow_realm',
  },
  {
    id: 'spell_soul_surge',
    name: 'Soul Surge',        nameKo: '영혼 파동',        nameZh: '灵魂涌动',
    type: 'spell', rarity: 'uncommon', cost: 2, icon: '⚡',
    desc:   'All towers deal +60% damage for 5 seconds.',
    descKo: '모든 타워 피해 +60%, 5초 지속.',
    descZh: '所有防御塔伤害+60%，持续5秒。',
    effect: { type: 'damage_boost_all', mult: 1.6, duration: 5000 },
    dlc: 'shadow_realm',
  },
  {
    id: 'spell_abyssal_wave',
    name: 'Abyssal Wave',      nameKo: '심연의 파도',      nameZh: '深渊浪潮',
    type: 'spell', rarity: 'rare', cost: 5, icon: '🌊',
    desc:   'Deal 50 damage to all enemies and slow them 30% for 4 seconds.',
    descKo: '모든 적에게 50 피해 및 4초 동안 30% 감속.',
    descZh: '对所有敌人造成50点伤害并减速30%，持续4秒。',
    effect: { type: 'nova', damage: 50, slowAmt: 0.3, slowDuration: 4000 },
    dlc: 'shadow_realm',
  },
  {
    id: 'spell_shadow_step',
    name: 'Shadow Step',       nameKo: '그림자 발걸음',       nameZh: '暗影步伐',
    type: 'spell', rarity: 'uncommon', cost: 3, icon: '🌀',
    desc:   'Teleport the 5 furthest enemies back to the spawn point.',
    descKo: '가장 앞선 적 5명을 스폰 지점으로 순간이동합니다.',
    descZh: '将最前方的5个敌人传送回出生点。',
    effect: { type: 'teleport_all', count: 5 },
    dlc: 'shadow_realm',
  },
  {
    id: 'spell_death_toll',
    name: 'Death Toll',        nameKo: '죽음의 값',        nameZh: '死亡丧钟',
    type: 'spell', rarity: 'common', cost: 1, icon: '🔔',
    desc:   'Gain 1 gold for each enemy killed so far this wave.',
    descKo: '이번 웨이브에서 처치한 적 1마리당 골드 1 획득.',
    descZh: '本波次至今每击杀1个敌人，获得1金币。',
    effect: { type: 'gold_per_wave_kill' },
    dlc: 'shadow_realm',
  },
  {
    id: 'spell_entropy_cascade',
    name: 'Entropy Cascade',   nameKo: '엔트로피 연쇄',   nameZh: '熵变连锁',
    type: 'spell', rarity: 'rare', cost: 4, icon: '🌪️',
    desc:   'Deal 50% of each enemy\'s current HP as damage. The more HP they have, the more they suffer.',
    descKo: '모든 적의 현재 HP 50%에 해당하는 피해. HP가 많을수록 더 큰 피해.',
    descZh: '对每个敌人造成其当前生命值50%的伤害。生命值越高，受创越重。',
    effect: { type: 'percent_hp_damage', percent: 0.5 },
    dlc: 'shadow_realm',
  },
  {
    id: 'spell_shadow_mend_2',
    name: 'Shadow Restoration', nameKo: '그림자 복원', nameZh: '暗影复原',
    type: 'spell', rarity: 'common', cost: 2, icon: '🖤',
    desc:   'Restore 1 Nexus HP. If already full, deal 30 damage to all enemies instead.',
    descKo: '넥서스 HP 1 회복. 이미 최대치라면 모든 적에게 30 피해.',
    descZh: '恢复1点要塞核心生命值。若已满，则改为对所有敌人造成30点伤害。',
    effect: { type: 'heal_nexus', amount: 1, goldOnFull: 0, altEffect: 'damage_all_30' },
    dlc: 'shadow_realm',
  },
  {
    id: 'spell_void_grasp',
    name: 'Void Grasp',        nameKo: '공허의 손길',        nameZh: '虚空掌握',
    type: 'spell', rarity: 'common', cost: 2, icon: '🤚',
    desc:   'Freeze all enemies for 3 seconds. The void holds them in place.',
    descKo: '모든 적을 3초 동안 빙결합니다. 공허가 그들을 붙잡습니다.',
    descZh: '冰冻所有敌人3秒。虚空将他们牢牢禁锢。',
    effect: { type: 'freeze', duration: 3000 },
    dlc: 'shadow_realm',
  },
];
